# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pethis?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#Mybatis-Plus输出日志
mybatis-plus:
  #configuration:
    # 日志输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl